name: compliance checks
permissions: {}

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.2.0
